language: go
sudo: require
dist: trusty
go:
  - 1.9.2
services:
  - mysql

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('haha') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo service mysql restart
  - mysql -e 'create database hello2;'
  - go get -v


