language: go
sudo: false
dist: trusty
go:
  - 1.9.2

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('mysql') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

before_install:
  - mysql -e 'create database hello2;'
  - go get -v


